spring:
  application:
    name: demo-docker-with-spring

  datasource:
    url: jdbc:mariadb://localhost:3307/test_docker_mariadb?useSSL=false&requireSSL=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect