services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_docker_mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
        ### 3307 -> Port on Host machine
        ### 3306 -> Port inside the container
        ### Connect to MariaDB on Host machine using port=3307
#    volumes:
#      - mariadb_data_volume:/var/lib/mysql
#
#volumes:
#  mariadb_data_volume: